### ISSUE TITLE
Segmentation fault on sulu:security:user:create

### ISSUE THREAD

**Issue by Aterkop** [sulu/skeleton#146]
Hi,
I've got an issue following Getting Started documentation to install sulu 2.3.7 (latest currently). At user creation step within "bin/adminconsole sulu:build dev" :
![adminconsole](https://user-images.githubusercontent.com/10169559/142448343-d7100029-018f-4258-a3c1-4bf309a89bf1.png)
All the database is created, role User is created but the user not and throw segmentation fault.

I've tried with "php ./bin/adminconsole sulu:security:user:create" and it's the same : Segmentation fault.
I have tried on 2 others Sulu previously installed in 2.3.0 and 2.3.6 and it works so it seems to be skeleton of 2.3.7... ?
Could you reproduce that bug ? To reproduce I only follow Getting started Steps (I tried many times, dropping database and creating again to be sure).
Really thanks in advance.

**Comment by chirimoya** [comment]
The version `2.5.2` of the `jms/metadata` package causes a segfault at the moment ... https://github.com/sulu/sulu/pull/6365#discussion_r751277912

**Comment by alexander-schranz** [comment]
Fixed by a new massive search bundle version: https://github.com/massiveart/MassiveSearchBundle/releases/tag/2.6.3. Run `composer update` to get the latest compatible version.

Thank you for reporting!
