### ISSUE TITLE
Problems building the administration interface frontend application

### ISSUE THREAD

**Issue by pmioni** [sulu/skeleton#158]
Sulu Version:  2.3.1
Platform: Ubuntu

#### Actual Behavior

When I modify assets/admin/index.js and launch the administration interface frontend application build, I get a set of errors in building React like the following:

```
ERROR in ./node_modules/sulu-admin-bundle/containers/List/fieldFilterTypes/AbstractFieldFilterType.js 9:8
Module parse failed: Unexpected token (9:8)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| import { action, observable } from 'mobx';
| let AbstractFieldFilterType = (_class = class AbstractFieldFilterType {
>   value = _initializerWarningHelper(_descriptor, this);
| 
|   constructor(onChange, parameters, value) {
```

This happens with all accepted node versions (12, 14), and using any of the possible options in 
https://docs.sulu.io/en/2.3/cookbook/build-admin-frontend.html
(command line, with docker, manually on local)

#### Expected Behavior

I expect that the libraries get built

#### Steps to Reproduce

This is difficult to reproduce, our site was created last year, and I was trying to get this done without updating the 2.3.1 version not to have to recheck all the application's codebase against the changes, as I just need to make minor changes to the admin interface. 

I tried to setup a 2.3.1 environment starting from Skeleton tag 2.3.1 but it is practically impossible to make it work, as most libraries included with composer have shifted versions.

#### Possible Solutions

Is there some missing React transpile instruction in Babel that we need to add? 
Maybe there's a conflict we created by using `symfony/webpack-encore-bundle` to create our own frontend build system? In theory the should not have a conflict, as it resides in a different folder from the admin build system.

Should we update to some version in the 2.3.*? As mentioned above, I would rather not if it's not unavoidable.

**Comment by chirimoya** [comment]
I think you need to update the webpack/babel configuration according to this PR https://github.com/sulu/skeleton/pull/155

**Comment by pmioni** [comment]
Thanks, in the end we decided to update to 2.3.9 and the issue went away.
