### ISSUE TITLE
[2.3] Admin interface fails to build

### ISSUE THREAD

**Issue by AdamReece-WebBox** [sulu/skeleton#228]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.3.13
| Browser Version | Google Chrome 116

#### Actual Behavior

The build from source process fails, both with `bin/adminconsole sulu:admin:update-build` and `npm run build`.

#### Expected Behavior

The build to succeed. (Obviously. 🙂)

#### Steps to Reproduce

Good afternoon,

I've currently spent all day trying to get the Sulu administration interface to build on a client project. There are modest changes injected in to:

* Add a category field for users
* Add a toolbar to an import section

I am however able to replicate the issue by commenting out the changes in our "app.js" and build just the Sulu administration interface "as is" from source. We haven't modified the "package.json", it's [fresh from 2.3.13](https://github.com/sulu/skeleton/blob/c6a7f47651741bf9c1d0a9b16a69ece0fb82c730/assets/admin/package.json).

We're using Node 14.21.3 and NPM 6.14.18. (Fetched via [NVM](https://github.com/nvm-sh/nvm).) A manual build process is as follows:

```bash
nvm use 14
rm -rf assets/admin/node_modules && rm -rf vendor/sulu/sulu/node_modules && rm -rf vendor/sulu/sulu/src/Sulu/Bundle/*/Resources/js/node_modules
rm -rf assets/admin/package-lock.json && rm -rf vendor/sulu/sulu/package-lock.json && rm -rf vendor/sulu/sulu/src/Sulu/Bundle/*/Resources/js/package-lock.json
cd ./assets/admin
npm cache clean --force
npm install
npm run build
```

It would appear there are issues with the following modules from the Sulu skeleton:

* sulu-admin-bundle/views/Tabs/Tabs.js
* sulu-admin-bundle/containers/Form/fields/Heading.js
* sulu-admin-bundle/containers/Form/fields/SmartContent.js
* sulu-admin-bundle/containers/List/stores/ListStore.js
* sulu-preview-bundle/containers/Preview/Preview.js
* sulu-admin-bundle/containers/Form/fields/Checkbox.js
* sulu-admin-bundle/containers/FieldBlocks/FieldBlocks.js
* sulu-page-bundle/views/List/itemActions/RestoreVersionItemAction.js
* sulu-page-bundle/containers/Form/fields/SegmentSelect.js
* sulu-admin-bundle/containers/Form/fields/SingleSelection.js
* sulu-admin-bundle/containers/Form/stores/MemoryFormStore.js
* sulu-security-bundle/containers/RolePermissions/SystemRolePermissions.js
* sulu-admin-bundle/containers/Form/stores/ResourceFormStore.js
* htmlparser2/lib/esm/index.js
* sulu-admin-bundle/containers/Form/conditionDataProviders/localeConditionDataProvider.js
* sulu-admin-bundle/containers/List/List.js
* sulu-page-bundle/containers/Form/fields/SettingsVersions.js

All of these with exception of the "htmlparser2" module all appear to be a syntax error due to the inability to use optional chaining. (E.g. `something?.id`)

#### Possible Solutions

I can solve most of the above by including the [@babel/plugin-transform-optional-chaining](https://babeljs.io/docs/babel-plugin-transform-optional-chaining) plug-in:

```bash
npm install --save-dev @babel/plugin-transform-optional-chaining
```

Then add a "@babel/plugin-transform-optional-chaining" line to the "plugins" array within file "babel.config.json":

```json
{
    "presets": [
        ["@babel/preset-env", {"useBuiltIns": "usage", "corejs": "3.18"}],
        "@babel/preset-react"
    ],
    "plugins": [
        ["@babel/plugin-proposal-decorators", {"legacy": true}],
        "@babel/plugin-transform-flow-strip-types",
        "@babel/plugin-transform-optional-chaining", // <<-- This
        "@babel/plugin-proposal-nullish-coalescing-operator",
        "@babel/plugin-proposal-class-properties"
    ],
    "assumptions": {
        "setPublicClassFields": true
    }
}
```

The other issue regarding [htmlparser2](https://www.npmjs.com/package/htmlparser2) I couldn't solve by just including the [domelementtype](https://www.npmjs.com/package/domelementtype) package. I found [another issue](https://github.com/fb55/htmlparser2/issues/1237#issuecomment-1182522861) suggesting downgrading it to version 7.2.0, including [@babel/plugin-proposal-export-namespace-from](https://babeljs.io/docs/babel-plugin-proposal-export-namespace-from), or including [@babel/plugin-transform-export-namespace-from](https://babeljs.io/docs/babel-plugin-transform-export-namespace-from), neither of which resolved this.

A bunch of other issues came up, which could be progress:

```log
ERROR in ./index.js
Module not found: Error: Can't resolve 'sulu-admin-bundle' in './assets/admin'

ERROR in ./index.js
Module not found: Error: Can't resolve 'sulu-audience-targeting-bundle' in './assets/admin'

ERROR in ./index.js
Module not found: Error: Can't resolve 'sulu-category-bundle' in './assets/admin'

ERROR in ./index.js
Module not found: Error: Can't resolve 'sulu-contact-bundle' in './assets/admin'

ERROR in ./index.js
Module not found: Error: Can't resolve 'sulu-custom-url-bundle' in './assets/admin'

ERROR in ./index.js
Module not found: Error: Can't resolve 'sulu-location-bundle' in './assets/admin'

ERROR in ./index.js
Module not found: Error: Can't resolve 'sulu-media-bundle' in './assets/admin'

ERROR in ./index.js
Module not found: Error: Can't resolve 'sulu-page-bundle' in './assets/admin'

ERROR in ./index.js
Module not found: Error: Can't resolve 'sulu-preview-bundle' in './assets/admin'

ERROR in ./index.js
Module not found: Error: Can't resolve 'sulu-route-bundle' in './assets/admin'

ERROR in ./index.js
Module not found: Error: Can't resolve 'sulu-search-bundle' in './assets/admin'

ERROR in ./index.js
Module not found: Error: Can't resolve 'sulu-security-bundle' in './assets/admin'

ERROR in ./index.js
Module not found: Error: Can't resolve 'sulu-snippet-bundle' in './assets/admin'

ERROR in ./index.js
Module not found: Error: Can't resolve 'sulu-website-bundle' in './assets/admin'
```

I tried `npm run preinstall` to get the Sulu bundles resolved though that brought me back to the "htmlparser2" issue with "domelementtype".

Where could I go from here?

Not sure if 2.3 is still maintained to any degree. I don't really have any more client time to spend bringing the project up to 2.4 and 2.5 unless there would be certainty that the above issue would be resolved by either of them.

**Comment by alexander-schranz** [comment]
To fix this issues you need to upgrade Sulu to the latest supported versions e.g. `2.4.14` or `2.5.10`: See also https://github.com/sulu/sulu/issues/6917

**Comment by AdamReece-WebBox** [comment]
Hi Alexander,

Thanks for your reply. Looks like going from 2.3 to 2.4 won't take anywhere near as long as 2.2 to 2.3.
I'll try this out tomorrow.

**Comment by AdamReece-WebBox** [comment]
Hi Alexander,

Thanks again -- Now on 2.4 the admin interface built first time without issue using the automatic "`sulu:admin:update-build`" command.
We'll make this point further to our client why such component upgrades matter.
