### ISSUE TITLE
.gitignore vs .gitkeep?

### ISSUE THREAD

**Issue by kfrohwein** [sulu/skeleton#24]
skeleton/src/Controller/Admin/.gitignore

Shouldn't the name be .gitkeep?

Same in /Website/

**Comment by alexander-schranz** [comment]
@kfrohwein symfony uses `.gitignore` as `.gitkeep` in there recipes, maybe we should switch all `.gitkeep` to `.gitignore` to avoid confusing @sulu/core-team what do you think?

**Comment by nnatter** [comment]
`.gitkeep` is used to commit an otherwise empty directory to the repository. this is needed because git does not commit empty directories. so i think renaming `skeleton/src/Controller/Admin/.gitignore` to `skeleton/src/Controller/Admin/.gitkeep` would be more correct 🙂

**Comment by alexander-schranz** [comment]
@nnatter sadly as said Symfony does use `.gitignore` for that instead of `.gitkeep`. If we rename all `.gitkeep` to `.gitignore`. Symfony flex would still create the `.gitkeep` files.

**Comment by danrot** [comment]
@alexander-schranz You mean it the other way round, right? Symfony flex would still create the `.gitignore` files.

What I don't like about `.gitkeep` is that it is just an empty file, that will never have content... Therefore I would prefer `.gitignore`. But the main reason is that Smyfony is using `.gitignore`, so I would say that is a no-brainer, and we just do exactly the same.

And I couldn't find any currently existing `.gitkeep` files :thinking: So I am not even sure if an action is required here.

**Comment by alexander-schranz** [comment]
@danrot correctly the other way around I mean it 🙈 

We have 3 .gitkeep files we maybe should rename them also to .gitignore.

**Comment by danrot** [comment]
Ah, now I've found them... I quickly create a PR, then we can close this issue again.

**Comment by airtonix** [comment]
> .gitkeep is used to commit an otherwise empty directory to the repository. this is needed because git does not commit empty directories. gitignore has another meaning imo.

> so i think renaming skeleton/src/Controller/Admin/.gitignore to skeleton/src/Controller/Admin/.gitkeep would be more correct ￼

There's no spec that says `.gitkeep` is official, it's just something someone started using because they didn't understand `.gitignore`: 

```
/*
!.gitignore
```

of if you only want the analgy of `.gitkeep` : 

```
!.gitignore
```

if you need to document why: 

```
# Hey guy: reasons 👍🏻 

/*
!.gitignore
```

**Comment by alexander-schranz** [comment]
We migrated from `.gitkeep` to `.gitignore`. At the end the `.gitignore` files are coming from symfony/recipes and sulu/skeleton is just the same as a symfony/skeleton project.
