### ISSUE TITLE
On install server:start is missing from bin/console

### ISSUE THREAD

**Issue by mrunkel** [sulu/skeleton#69]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.1.1
| Browser Version | N/A

#### Actual Behavior

After install and creation of the site, I can't start the server because the command server:start is missing from bin/console.  server:dump and server:log are present.

#### Expected Behavior

Per the getting started guide, bin/console server:start should start a webserver.

#### Steps to Reproduce

I just followed the getting started guide https://docs.sulu.io/en/2.0/book/getting-started.html

**Comment by mrunkel** [comment]
Okay, never mind..  I switched the getting started guide to v2.0 where a different command is given.

symfony server:start also seems to work in this case.

You might want to change the link from the https://sulu.io/blog/adding-sulu-cms-to-an-existing-symfony-project page to use the latest docs?

**Comment by alexander-schranz** [comment]
@mrunkel the webserver bundle has been removed in symfony 5, the command in the [2.1 docs](https://docs.sulu.io/en/2.1/book/getting-started.html#start-a-web-server) will use the php internal server so no additional installation is needed, we only choose that as thats the quickest start into sulu without install anything else, you definitely free to use any other webserver you want.

**Comment by mrunkel** [comment]
Understood, my only suggestion is to fix the links on the https://sulu.io/blog/adding-sulu-cms-to-an-existing-symfony-project page so that they link to latest and not 2.0 of the docs.

**Comment by alexander-schranz** [comment]
@mrunkel updated the link to the current version. Thank you!

**Comment by mrunkel** [comment]
No no.. Thank you! :)
