### ISSUE TITLE
PHP 8 compatibility from latest Sulu releases was not adjusted in skeleton

### ISSUE THREAD

**Issue by renecatharsis** [sulu/skeleton#93]
| Q | A
| --- | ---
| Bug? | yes?
| New Feature? | no
| Sulu Version | 2.1.9 & 2.2.5
| Browser Version | n/a

#### Actual Behavior
composer create-project sulu/skeleton fails to install on PHP 8
`[InvalidArgumentException]
  Could not find package sulu/skeleton with stability stable in a version installable using your PHP version, PHP extensions and Composer version.`

#### Expected Behavior
Installation runs without composer refusing to proceed

#### Steps to Reproduce
Execute the composer create-project command on any system running PHP 8

#### Possible Solutions
Adjust compose.json php requirements according to the changes to sulu itself for v2.1.9 and v2.2.5
It currently only allows `^7.2` instead of `^7.2 || ^8.0`

**Comment by alexander-schranz** [comment]
@renecatharsis Thank you for reporting. https://github.com/sulu/skeleton/issues/93 should fix this.
